// <auto-generated />
using System;
using EvidenciaStudentov.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_NET_Bakalarka.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250210072137_PLS")]
    partial class PLS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EvidenciaStudentov.Models.Dochadzka", b =>
                {
                    b.Property<int>("DochazkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DochazkaId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("JePritomny")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PouzivatelId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("DochazkaId");

                    b.HasIndex("PouzivatelId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Dochadzky");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Pouzivatel", b =>
                {
                    b.Property<int>("PouzivatelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PouzivatelId"));

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PouzivatelId");

                    b.ToTable("Pouzivatelia");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Predmet", b =>
                {
                    b.Property<int>("PredmetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PredmetId"));

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UcitelId")
                        .HasColumnType("int");

                    b.HasKey("PredmetId");

                    b.HasIndex("UcitelId");

                    b.ToTable("Predmety");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.PriradeniePredmetovUcitelom", b =>
                {
                    b.Property<int>("PriradeniePredUcitelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PriradeniePredUcitelId"));

                    b.Property<int>("PouzivatelId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("PriradeniePredUcitelId");

                    b.HasIndex("PouzivatelId");

                    b.HasIndex("PredmetId");

                    b.ToTable("PriradeniaPredmetovUcitelom");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.PriradeniePredmetovZiakom", b =>
                {
                    b.Property<int>("PriradeniePredZiakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PriradeniePredZiakId"));

                    b.Property<int>("PouzivatelId")
                        .HasColumnType("int");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("PriradeniePredZiakId");

                    b.HasIndex("PouzivatelId");

                    b.HasIndex("PredmetId");

                    b.ToTable("PriradeniePredmetovZiakom");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Znamka", b =>
                {
                    b.Property<int>("ZnamkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZnamkaId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Hodnota")
                        .HasColumnType("int");

                    b.Property<int>("PouzivatelId")
                        .HasColumnType("int");

                    b.Property<string>("Poznamka")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PredmetId")
                        .HasColumnType("int");

                    b.HasKey("ZnamkaId");

                    b.HasIndex("PouzivatelId");

                    b.HasIndex("PredmetId");

                    b.ToTable("Znamky");
                });

            modelBuilder.Entity("EvidenciaStudentov.ViewModels.PredmetViewModel", b =>
                {
                    b.Property<int>("PredmetViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PredmetViewId"));

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PocetZiakov")
                        .HasColumnType("int");

                    b.Property<string>("Popis")
                        .HasColumnType("longtext");

                    b.Property<string>("Ucitel")
                        .HasColumnType("longtext");

                    b.HasKey("PredmetViewId");

                    b.ToTable("PredmetViewModel");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Dochadzka", b =>
                {
                    b.HasOne("EvidenciaStudentov.Models.Pouzivatel", "Pouzivatel")
                        .WithMany("Dochazky")
                        .HasForeignKey("PouzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenciaStudentov.Models.Predmet", "Predmet")
                        .WithMany("Dochazky")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pouzivatel");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Predmet", b =>
                {
                    b.HasOne("EvidenciaStudentov.Models.Pouzivatel", "Ucitel")
                        .WithMany()
                        .HasForeignKey("UcitelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ucitel");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.PriradeniePredmetovUcitelom", b =>
                {
                    b.HasOne("EvidenciaStudentov.Models.Pouzivatel", "Pouzivatel")
                        .WithMany("PriradenePredmetyUcitelom")
                        .HasForeignKey("PouzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenciaStudentov.Models.Predmet", "Predmet")
                        .WithMany("PriradenePredmetyUcitelom")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pouzivatel");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.PriradeniePredmetovZiakom", b =>
                {
                    b.HasOne("EvidenciaStudentov.Models.Pouzivatel", "Pouzivatel")
                        .WithMany("PriradeniePredmetovZiakom")
                        .HasForeignKey("PouzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenciaStudentov.Models.Predmet", "Predmet")
                        .WithMany("PriradeniePredmetovZiakom")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pouzivatel");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Znamka", b =>
                {
                    b.HasOne("EvidenciaStudentov.Models.Pouzivatel", "Pouzivatel")
                        .WithMany("Znamky")
                        .HasForeignKey("PouzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvidenciaStudentov.Models.Predmet", "Predmet")
                        .WithMany("Znamky")
                        .HasForeignKey("PredmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pouzivatel");

                    b.Navigation("Predmet");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Pouzivatel", b =>
                {
                    b.Navigation("Dochazky");

                    b.Navigation("PriradenePredmetyUcitelom");

                    b.Navigation("PriradeniePredmetovZiakom");

                    b.Navigation("Znamky");
                });

            modelBuilder.Entity("EvidenciaStudentov.Models.Predmet", b =>
                {
                    b.Navigation("Dochazky");

                    b.Navigation("PriradenePredmetyUcitelom");

                    b.Navigation("PriradeniePredmetovZiakom");

                    b.Navigation("Znamky");
                });
#pragma warning restore 612, 618
        }
    }
}


